theme: jekyll-theme-slate
title: "Leaving Cert Notes"
description: "My website full of Notes for the (Irish) Leaving Cert"
author: "CutThroat78"
show_downloads: false
github:
   is_project_page: false